function [plots,annotations]=plot_fun(plots,annotations,x,speed,position_norm,v,p,tf_sc,trail_color,OE)

        format short

        plots(3)=plot3(x(:,1),x(:,2),x(:,3),'o',...
        'MarkerEdgeColor',trail_color,...
        'MarkerFaceColor',trail_color,...
        'MarkerSize',4);    %spacecraft path
        plots(2)=plot3(p(1),p(2),p(3),'bo',...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[.49 1 .63],...
        'MarkerSize',10);   %spacecraft
    
    
        annotations(1)=annotation('textbox', [0, .9, .3, .1], 'string', "v (magnitude): "+speed+" km/s",'Color','w','LineStyle','none');
        annotations(2)=annotation('textbox', [0, .8, .3, .1], 'string', "v (vectorized): ["+...
            v(1)+","+v(2)+","+v(3)+"]"+" km/s",'Color','w','LineStyle','none');
        annotations(3)=annotation('textbox', [0, .7, .3, .1], 'string', "r (magnitude): "+position_norm+" km",'Color','w','LineStyle','none');
        annotations(4)=annotation('textbox', [0, .6, .3, .1], 'string', "r (vectorized): ["+...
            p(1)+","+p(2)+","+p(3)+"]"+" km",'Color','w','LineStyle','none');
        annotations(5)=annotation('textbox', [0, .5, .3, .1], 'string', "time warp: x"+tf_sc,'Color','w','LineStyle','none');
        annotations(6)=annotation('textbox', [0, .2, .3, .1], 'string',...
            "Orbital Elements"+newline+"a: "+OE(2)+newline+"e: "+OE(3)+newline+"i: "+OE(4)+newline+"AoP: "...
            +OE(5)+newline+"LAN: "+OE(6)+newline,'Color','w','LineStyle','none');
end